import pandas as pd
import requests
from bs4 import BeautifulSoup as bs

# Read the STATA dataset "investments_data" into pandas
inv_2 = pd.DataFrame(pd.read_stata("investments_data.dta", convert_categoricals=False))

#In order to get the set of municipalities included in the experiment,
#we recreated the INEGI codes from the data available in the investment data set

# the codes are 5 digits (ex. 12004) where the first two digits are the state(12)
# and the next three(004) are the municipality in that state

inv_2['st_muni']=inv_2['state'].astype(str).str.cat(inv_2['muni'].astype(str).str.zfill(3))

#Get all unique INEGI municipality codes
c=inv_2['st_muni'].unique().tolist()

# Scrape the hidden API from the INEGI website for the
# indicator code "5300000098"
manu_data=pd.DataFrame()
for line in c:
    # Some municipalities dont have data for the indicator
    # Bypassing the error messages generated by such munis
    try:
        link=("http://www.beta.inegi.org.mx/app/api/indicadores/interna_v1_1//ValorIndicador/5300000098/{}/null/es/null/null/3/pd/null/null/null/null/null/xml/563cbaa8-58bb-fef8-6763-1f1dae318f99".format(line))
        resp = requests.get(link)
        xml = resp.content
        soup = bs(xml, "lxml")

        #Find the name of the municipalities
        name=soup.find("municipality")
        n=name.find('a:value').contents[0]

        #Find the data for the indicator for all the avalilable years
        values=soup.find("value").findChildren()
        v=[]
        for i in range(0,len(values)):
            v.append(values[i].contents[0])

        #Find years for which data is available
        period=soup.find("periods").findChildren()
        p3=period[int(len(period)/4+1)].findChildren()
        p=[]
        # length of the tag varies according to the number of years
        # for which data is available
        if len(p3)==9:
            for i in (2,5,8):
                p.append(p3[i].contents[0])
            colnames=["code","name",p[0],p[1],p[2]]
            list=[(line,n,v[0],v[1],v[2])]
        elif len(p3)==6:
            for i in (2,5):
                p.append(p3[i].contents[0])
            colnames=["code","name",p[0],p[1]]
            list=[(line,n,v[0],v[1])]
        else:
            p.append(p3[2].contents[0])
            colnames=["code","name",p[0]]
            list=[(line,n,v[0])]

        #Append all data for the specific muni into "data"
        data=pd.DataFrame(list,columns=colnames)
        #Apend data from particular muni into overall dataset
        manu_data=manu_data.append(data,ignore_index=True)

    except:
        pass

# Write the file as CSV
manu_data.to_csv("muni_manu_data.csv", sep=',', encoding='utf-8',index=False)
